import { fig, h2, h3, ol, p, sep, stats, ul, type Block } from "./blocks";
import { AUTHOR } from "./site";

/* Текст перенесено з опублікованої HTML-версії автоматично, символ у символ.
   Кожен абзац, заголовок, пункт списку й підпис звірено з оригіналом. */

export const designEngineer2026 = {
  href: "/articles/design-engineer-2026",
  title: "Design Engineer у 2026: хто це і хто наймає",
  metaTitle: "Design Engineer у 2026: хто це і хто наймає",
  metaDescription:
    "Дослідження ролі design engineer за даними 2026 року. Глобальні вакансії з вилками, зведений профіль вимог, текстовий аналіз 247 дизайнерських вакансій DOU і шлях переходу з продуктового дизайну.",
  ogTitle: "Design Engineer у 2026: дослідження ролі",
  ogDescription: "Глобальні вакансії Anthropic, Vercel, Cursor і Ramp, профіль вимог і глибокий зріз українського ринку за 247 вакансіями DOU.",

  lead: [
    "Design engineer проєктує інтерфейс і сам доводить його до продакшн-коду. За останній рік цю роль відкривали Anthropic, Vercel, Cursor, Ramp і Lovable, а в Україні вона ще ховається під назвами UX Designer чи Product Designer.",
    "Я сама почала працювати дизайн-інженером, і мені було цікаво розібратися, як ця роль виглядає на ринку зараз і що я маю покривати на цій позиції. Я порівняла глобальний ринок з українським. Глобальний задає стандарт: хто наймає, що вимагає, скільки платить, як проводить співбесіду. І український: що показали тексти 382 дизайнерських і 147 фронтенд-вакансій з DOU та Djinni. Скільки заробляють дизайнери проти розробників, хто вже працює в цій ролі і як я шукала таку роботу. Наприкінці зведений список вимог до професії і висновки, що з усім цим робити. Дослідження я робила з допомогою моделі Claude Fable 5.",
  ],

  byline: { name: AUTHOR, date: "25 серпня 2026", avatar: "/articles/img/author.jpg" },

  /* Стоїть над заголовком, а не під ним: кадр не ілюструє якусь одну тезу, він
     задає тон усьому тексту, тож читач має зустріти його першим. */
  hero: {
    src: "/articles/img/design-engineer-2026-lede.png",
    alt: "Аркуш у лінійку зі словами з вакансій design engineer, набраними синім моноширинним шрифтом: craft, taste, polish, ownership, vibe coding, tokens, prompt to production, no handoff, Figma to code, Vercel, Claude Code, Cursor, AI-native, agentic. Кілька слів замальовано коректором.",
    width: 2880,
    height: 928,
  },

  blocks: [
  p("Мене звати Настя, я продуктова дизайнерка з понад п'ятирічним досвідом розробки інтерфейсів для агенцій, стартапів і корпоративних продуктів. Зараз я вже працюю дизайн-інженером і поєдную дизайн із фронтендом на комерційному проєкті."),
  p("Зміст"),
  ol(
    <><a href="#who">Хто такий design engineer</a></>,
    <><a href="#change">Що змінилось у роботі дизайнера за останній рік</a></>,
    <><a href="#hiring">Хто наймає і скільки платить</a></>,
    <><a href="#ukraine">А що в Україні</a></>,
    <><a href="#requirements">Вимоги до професії: зведений список</a></>,
    <><a href="#interview">Співбесіда і портфоліо</a></>,
    <><a href="#summary">Підсумуємо</a></>,
  ),
  h2("who", "Хто такий design engineer"),
  p("Design engineer працює на стику продуктового дизайну і фронтенду. Дизайнер здає макет і опис станів, які далі збирає розробник. Design engineer здає готовий компонент у кодовій базі: зі станами, анімацією, доступністю і поведінкою на різних екранах. Проміжних артефактів для передачі в такій роботі немає, бо передавати нікому. Звідси й слова, якими описують роль у вакансіях: ownership, крафт і senior-планка."),
  p(<>Термін має коротку історію, <a href="https://luhr.co/blog/2024/02/26/the-origins-of-design-engineering/" target="_blank" rel="noopener">її хронологію зібрав Девід Лур</a>. Останні десять років схожі гібридні ролі ховалися під назвами UI engineer, UX engineer чи full-stack designer. Одна з перших книжок про професію, <a href="https://designbetterpodcast.com/p/design-engineering-handbook" target="_blank" rel="noopener">Design Engineering Handbook</a>, вийшла у 2020 році. Її написали Наталя Шелберн і колеги з New York Times, Mailchimp, Minted та Indeed. Сам термін, за словами Шелберн, вона придумала разом з Аарроном Волтером на конференції в Сіднеї. У 2022-му індустрією розійшлося есе Джима Нільсена <a href="https://blog.jim-nielsen.com/2022/the-case-for-design-engineers/" target="_blank" rel="noopener">«The Case for Design Engineers»</a>, а у 2024-му Vercel <a href="https://vercel.com/blog/design-engineering-at-vercel" target="_blank" rel="noopener">розповів у блозі</a>, як його design engineers працюють у трьох режимах: поруч із дизайнерами, всередині продуктових команд і самостійно, від ескізу до релізу. Масовою назва стала у 2024–2026, коли дизайнери отримали інструменти, з якими макет можна самому довести до робочого коду, навіть не вміючи його писати.</>),
  sep(),
  h2("change", "Що змінилось у роботі дизайнера за останній рік"),
  p(<>У травні 2026 року Designer Fund і Foundation Capital запустили <a href="https://stateofaidesign.com/" target="_blank" rel="noopener">AI in Design Report</a>, який доповнювали до серпня: опитування 900+ дизайнерів із 60+ країн.</>),
  stats({ value: "50%", label: "дизайнерів уже відправляли AI-згенерований код у продакшн" }, { value: "65%", label: "кажуть, що виконують більше інженерних і PM-задач, ніж рік тому" }, { value: "20%", label: "опитаних називають себе design engineer" }),
  p("Порівняння з торішнім заміром показує швидкість зміни. Щотижневе використання AI у дизайні зросло з 54% у 2025 до 91% у 2026. Для 43% опитаних робочий прототип уже входить в очікуваний результат роботи. Є і зворотний бік. Частка дизайнерів, які відзначають зниження співпраці в команді, зросла з 5% до 20%. Час перетікає з живих обговорень у промпти й термінали."),
  p("Виробництво інтерфейсу подешевшало, бо агент генерує компонент за хвилини. Дизайн при цьому не подешевшав: для 80% дизайнерів AI допомагає, але не замінює власне чуття якості, і лише 5% керівників стали менше цінувати якість виконання. Половина керівників, наймаючи дизайнерів, тепер більше зважає на володіння AI."),
  p(<>Figma підтверджує цей вектор в іншому дослідженні. У <a href="https://www.figma.com/blog/why-demand-for-designers-is-on-the-rise/" target="_blank" rel="noopener">лютневому опитуванні менеджерів з найму</a> 82% кажуть, що потреба в дизайнерах зросла або стабільна, а 73% бачать зростання потреби у володінні AI-інструментами. Попит на senior-дизайнерів росте у 56% компаній, на джуніорів у 25%.</>),
  p(<>Роль показують і публічно. Anthropic на Code w/ Claude 2026 у доповіді <a href="https://www.youtube.com/watch?v=Uvl-tRga98g" target="_blank" rel="noopener">«Designing with Claude: From prompt to production»</a> показала, як невелика команда зібрала Claude Design від промпту до продакшену.</>),
  sep(),
  h2("hiring", "Хто наймає і скільки платить"),
  p(<>В інтернеті я натрапляла на кілька дошок, де збирають вакансії саме для design engineers. Для прикладу візьмемо <a href="https://www.designengineerjob.com/" target="_blank" rel="noopener">designengineerjob.com</a> разом із кар&#39;єрними сторінками компаній, зріз на кінець серпня 2026 року, ролі у вебі та продукті. Це вакансії Anthropic, Vercel, Cursor, Replit, Ramp, Lovable, Supabase, Runway, Cloudflare, Airtable, Meta та інших. Близько половини оголошень на дошці датовані травнем, решта переважно квітнем, тож повної картини ринку зріз не дає, але ґрунт для розуміння позиції зібрати можна.</>),
  fig("/articles/img/board-designengineerjob.jpg", "Скріншот дошки designengineerjob.com: список вакансій design engineer у Runway, Mintlify, Console, OpenAI, Hex, Vercel з зарплатними вилками", "wide", 2272, 1538, "Дошка designengineerjob.com, 24.08.2026: Runway $250–310k, Console $200–350k, Mintlify $145–200k."),
  p("Тайтл «Design Engineer» стоїть у більшості вакансій, варіанти на кшталт Design Technologist чи Creative Coder трапляються поодиноко. Повністю віддалених ролей третина, але ремоут не означає «звідусіль». У частині тайтлів прямо стоїть Senior, Staff, Lead або Principal, у решті рівень захований у вимоги на 4–7+ років досвіду."),
  p("Вимоги в цих вакансіях повторюються майже дослівно. Cursor шукає людину, «equally comfortable in Figma and your code editor», зі стеком TypeScript, React, SolidJS, CSS і анімаціями. Vercel чекав від кандидата «highest level of polish», ця вакансія вже закрита. Anthropic записує доступність і performance budgets у зону його відповідальності. Lovable просить «sharp eye for craft», а на технічному скринінгу оцінює кандидата на рівні product engineer. Ramp ставить «Claude» тегом навички поруч із React. Повний профіль вимог, зведений з усіх вакансій, буде нижче в окремому розділі."),
  sep(),
  h2("ukraine", "А що в Україні"),
  p(<><a href="https://jobs.dou.ua/vacancies/?search=design+engineer" target="_blank" rel="noopener">Пошук «design engineer» на DOU</a> повертає 40 вакансій. Майже всі це інженери-конструктори з miltech: БпЛА, електроніка, RF-системи. Профільних дві: Cracken з Design Engineer у назві, і Cieden, де роль захована під «UX Designer». Окремої категорії «Design Engineer» ще немає ні на DOU, ні на <a href="https://djinni.co/jobs/" target="_blank" rel="noopener">Djinni</a>.</>),
  p(<><a href="https://djinni.co/jobs/?all_keywords=design+engineer" target="_blank" rel="noopener">Пошук «design engineer» на Djinni</a> дає 61 вакансію, але профільна тільки одна: <a href="https://djinni.co/jobs/844161-product-design-engineer/" target="_blank" rel="noopener">DOOR3</a>, американська компанія, яка 20 серпня відкрила ремоут-позицію Product Design Engineer із формулюванням «one craft, not two stages with a handoff between them». Але в полі країн стоїть EU, тобто з профілем «Україна» подати заявку не вийде.</>),
  p("Про вибірку: усі вакансії, що висіли 27.08.2026 на DOU у категоріях Design (247) і Front End (86) та на Djinni у дизайнерських категоріях (164 унікальні) і в JavaScript та React.js (64). Скрипт завантажив повний текст кожної і шукав ключові слова: інструменти, технології, AI в усіх формах і згадки про код. Вакансії, що висять і на DOU, і на Djinni, зведені за парою «компанія плюс назва»: 29 таких збігів серед дизайнерських і 3 серед фронтендних. Після зведення лишилося 382 дизайнерські вакансії і 147 фронтендних."),
  stats({ value: "4 із 382", label: "дизайнерських вакансій на DOU і Djinni просять design engineer по суті: дизайн і код в одній ролі" }, { value: "34 із 382", label: "згадують Claude, ще 15 Cursor, 9 v0 або Bolt, 4 Lovable. AI як інструмент для коду є у 10% описів" }, { value: "196 із 382", label: "містять слово AI в будь-якій формі. Половина ринку вже пише про AI, але здебільшого як про генерацію картинок" }),
  p("React згадують 16 дизайнерських вакансій із 382, TypeScript 4, HTML і CSS 48, Storybook 6. Тобто код як вимога до дизайнера є у 4% описів. Для порівняння, у 147 фронтенд-вакансіях Claude згадують 24, а одна прямо просить «Figma skills with a design engineer mindset»."),
  p(<>На Djinni 133 дизайнерські вакансії зі 164 повністю віддалені, на DOU 86 із 247. Єдина трейні-вакансія: <a href="https://djinni.co/jobs/820758-trainee-ux-ui-engineer/" target="_blank" rel="noopener">jito.dev шукає Trainee UX/UI engineer</a>, стажера, який працюватиме з Claude Code і Storybook, щоб «розуміти і правити фронтенд» під власні макети. Формулювання з опису: «You shouldn&#39;t fear that AI will take your job; you should be the one who uses AI to do the work of three people». На цю вакансію 205 відгуків.</>),
  h3("", "Тепер детальніше глянемо на самі вакансії"),
  p(<><a href="https://jobs.dou.ua/companies/cieden/vacancies/367320/" target="_blank" rel="noopener">Cieden, UX Designer (AI-Native / Design Engineer)</a>, дизайн-агенція, заснована у Львові 2016 року, зараз зареєстрована в Торонто з розподіленою командою на 40+ людей. Рівень middle, два-три роки досвіду. «Your delivery is a Vercel link, not just a deck». «Pet Projects: This is huge for us. We want to see your deployed side projects with real code». «Claude Code Mastery: Custom commands, agents, and workflow scripting». Figma в їхньому стеку описана як інструмент «for strategy and assets, not as the source of truth».</>),
  fig("/articles/img/cieden-dou.jpg", "Скріншот вакансії Cieden UX Designer (AI-Native / Design Engineer) на DOU: вимоги Pet Projects with real code, Claude Code Mastery, Prototyping in Figma, Claude Code, Stitch", "mid", 1834, 1518, "Cieden на DOU: «Pet Projects: This is huge for us. We want to see your deployed side projects with real code» і «Claude Code Mastery: Custom commands, agents, and workflow scripting»."),
  p(<><a href="https://jobs.dou.ua/companies/onepage-gmbh/vacancies/369135/" target="_blank" rel="noopener">Onepage</a>, конструктор сайтів, зроблений українцями, шукає Senior Product Designer й пише: «Ви збираєте швидкі прототипи в Figma, в коді, через Cursor і Claude Code». І далі: «якщо своїх навичок HTML, CSS чи React поки немає, важливо бути готовим заходити туди через Cursor і Claude Code».</>),
  p(<><a href="https://jobs.dou.ua/companies/spaceberry/vacancies/367616/" target="_blank" rel="noopener">Spaceberry Studio</a> шукає Strong Junior UX/UI Designer, і серед задач стоїть «Build products from your own designs using an agentic development approach with tools such as Claude Code, Codex, and Cursor».</>),
  h3("", "Скільки платять"),
  p(<>Зарплатні зрізи DOU за літо 2026 дають дві медіани, які варто поставити поруч: <a href="https://dou.ua/lenta/articles/salary-report-non-tech-summer-2026/" target="_blank" rel="noopener">дизайнерів</a> і <a href="https://dou.ua/lenta/articles/salary-report-devs-summer-2026/" target="_blank" rel="noopener">розробників</a>.</>),
  stats({ value: "$2 475", label: "медіана дизайнера, UI/UX і Product Design, 307 респондентів" }, { value: "$3 500", label: "медіана розробника, 4 541 респондент" }),
  p("Різниця понад тисячу доларів на місяць, і з досвідом вона не зникає. Дизайнер із 10+ роками досвіду має медіану $3 550, senior-розробник $4 500, техлід $5 500. Українських вилок для design engineer поки немає, але на глобальному ринку цю роль оплачують за інженерною шкалою, бо людина відповідає за код у продакшені. Для дизайнера це рух у бік вищої вилки."),
  h3("", "Сфера в Україні вже розвивається"),
  p(<>За 2026 рік на DOU вийшло щонайменше чотири матеріали від людей, які поєднують дизайн і код. <a href="https://dou.ua/forums/topic/60864/" target="_blank" rel="noopener">Марія Нечипорук</a> пише про скіли для Claude Code, <a href="https://dou.ua/forums/topic/61294/" target="_blank" rel="noopener">Денис Осадчий</a> про власний міст між Figma і Claude Code, <a href="https://dou.ua/forums/topic/59081/" target="_blank" rel="noopener">Олена Івлєва</a> про межу між генерацією і продуктом, <a href="https://dou.ua/forums/topic/60149/" target="_blank" rel="noopener">Яна Лізгова</a> про магазин, зібраний з Claude Code. І трохи пишу про це я.</>),
  p(<>Поруч з&#39;являються курси. <a href="https://volomydyr.com/" target="_blank" rel="noopener">Володимир Мерленко</a> з Cieden випустив плагін Design Engineer для Claude Code, доступ за донат у фонд KOLO. <a href="https://prjctr.com/course/build-your-startup-with-ai" target="_blank" rel="noopener">Projector</a> запускає «Build Your Startup with AI».</>),
  h3("", "Як я шукала роботу інженером"),
  p("Вакансій із назвою «design engineer» таки досить мало, як ви бачите. Тому я почала зі старого доброго способу і писала людям, з якими раніше працювала. Питала, чи є у них або в їхніх знайомих задача, де потрібен саме дизайн-інженер. Так знайшовся проєкт, який я зараз веду вже другий місяць."),
  sep(),
  h2("requirements", "Вимоги до професії: зведений список"),
  p("За американськими, європейськими та українськими вакансіями, розділено за тим, як часто повторюються."),
  h3("", "Повторюється майже в кожній вакансії"),
  ul(
    "Фронтенд: React, TypeScript, семантичний HTML і сучасний CSS.",
    "Ownership: вести інтерфейс від ідеї до продакшену самостійно.",
    "Дизайн-система в коді: компоненти зі станами, токени, стандарти.",
    "Motion і мікроінтеракції: Framer Motion, CSS-анімації, чуття таймінгу.",
    "Прототипування в коді як щоденний спосіб роботи.",
    "Крафт: типографіка, лейаут, деталі.",
    "Доступність, адаптивність і продуктивність: семантика, фокус-стани, reduced motion, Core Web Vitals.",
    "AI-інструменти в щоденному процесі, Claude Code і Cursor, плюс власна оцінка того, що вони видають.",
    "Figma, однаково впевнено з редактором коду.",
    "Портфоліо з живими продуктами або робочими прототипами замість макетів.",
    "Комунікація: робота в парі з дизайнерами, інженерами й маркетологами, зрозуміле письмо.",
  ),
  h3("", "Зустрічається залежно від компанії"),
  ul(
    "Продуктове мислення: думати як PM, будувати як інженер.",
    "Самостійність без дизайн-команди, типово для стартапів.",
    "Перевірка прототипів на користувачах.",
    "Менторство і стандарти для команди у senior- і staff-ролях.",
    "Маркетингові сайти, конверсійні експерименти, SEO й аналітика у ролях Web & Brand.",
    "Headless CMS і контент-інфраструктура для великих сайтів.",
    "Інструменти для команди: плагіни для Figma, MCP-інтеграції, власні агенти й скіли.",
    "Інтеракційні патерни для AI-продуктів: показати, що робить агент, і дати людині це перевірити.",
    "Складні веб-інтеракції: WebGL, 3D, візуалізація даних.",
    "Англійська B2+ в українських і ремоут-вакансіях.",
  ),
  h3("", "Вимоги з інших ролей: варто розпізнавати"),
  ul(
    "Технічний скринінг на рівні product engineer, архітектура і performance budgets. Це планка staff-інженера.",
    "Деплої, технічний SEO, локалізація, incident response. Це інженер веб-платформи.",
    "Electron і нативні UI-фреймворки. Це десктоп-розробник.",
    "Перевести всю команду на AI-процес. Це лідерська роль.",
  ),
  sep(),
  h2("interview", "Співбесіда і портфоліо"),
  p(<>У компаній, які публічно описують процес, спільне одне: вас просять щось збудувати. Linear після розмов із рекрутером, менеджером і командою дає <a href="https://linear.app/now/why-and-how-we-do-work-trials-at-linear" target="_blank" rel="noopener">оплачуваний work trial</a> на два-п&#39;ять днів з доступом до Slack, Notion, GitHub і Figma. Оцінюють taste, judgment, ownership і product sense. <a href="https://jobs.ashbyhq.com/lovable/51885ae5-4f4c-46c4-abd3-d7aad1c8d9c0" target="_blank" rel="noopener">Lovable</a> проводить технічні інтерв&#39;ю зі скринінгом на рівні product engineer і «в окремих випадках» оплачувану тестову роботу. Класичного портфоліо-рев&#39;ю з гортанням кейсів майже не буває. За спостереженням <a href="https://verifiedinsider.substack.com/p/faq-design-hiring-in-2026" target="_blank" rel="noopener">Тома Скотта</a> з Verified Insider, команди просять незакінчені файли й процес роботи, а володіння AI стало найпомітнішою лінією поділу між кандидатами.</>),
  p(<>Портфоліо design engineer починається з власного сайту: зробленого самостійно, з власними інтеракціями. Далі йдуть компоненти — з порожніми станами, станами помилки й доступністю, закладеною від початку. <a href="https://uithings.com/design-engineering" target="_blank" rel="noopener">Гайд The Complete Guide to Design Engineering</a> радить показувати їх у публічному Storybook із документацією, а поруч лишати історію комітів, з якої видно, як ви доводили деталі.</>),
  sep(),
  h2("summary", "Підсумуємо"),
  ul(
    "В Україні половина дизайнерських вакансій згадує AI, 9% просять Claude чи Cursor, 4% React і лише 1% по суті шукає design engineer. У вакансіях уже просять дизайнера з інженерними навичками, але окремої посади й категорії під це ще не з'явилось.",
    "В Україні у роль можна зайти раніше, ніж на глобальному ринку. Там джуніорських вакансій нуль і планка 4–7+ років. Тут middle бере Cieden, junior Spaceberry, трейні jito.dev, хоч і без слова engineer у посаді.",
    "Медіана розробника в Україні на тисячу доларів вища за медіану дизайнера, і з досвідом розрив не зникає. На глобальному ринку design engineer оплачується за інженерною шкалою, українських даних по цій ролі поки немає.",
  ),
  p("Що з цим робити:"),
  ul(
    "Переводьте портфоліо на власний сайт, свої компоненти зі станами, Storybook, історія комітів.",
    "Шукайте вакансії за словами в описі: Claude Code, Cursor, React, prototype.",
    <>Починайте практикувати. Візьміть маленький власний біль, який давно хотілось закрити, і зберіть його як робочу річ без Figma, одразу через генерацію. Так ви звикнете до процесу, коли інтерфейс народжується з промпту. Anthropic щойно відкрила <a href="https://academy.claude.com/" target="_blank" rel="noopener">Claude Academy</a>, безкоштовні курси й туторіали по Claude Code, там можна перевірити на собі все, що описано вище.</>,
  ),
  sep(),
  h2("", "Джерела"),
  ol(
    <><a href="https://stateofaidesign.com/" target="_blank" rel="noopener">AI in Design Report 2026</a> (Designer Fund × Foundation Capital, травень 2026, доповнення до серпня), розділи Tools, Craft, Teams</>,
    <><a href="https://www.figma.com/blog/why-demand-for-designers-is-on-the-rise/" target="_blank" rel="noopener">Figma: Why Demand for Designers Is on the Rise</a> (опитування менеджерів з найму, 10.02.2026)</>,
    <><a href="https://vercel.com/blog/design-engineering-at-vercel" target="_blank" rel="noopener">Design Engineering at Vercel</a> (29.03.2024)</>,
    <><a href="https://luhr.co/blog/2024/02/26/the-origins-of-design-engineering/" target="_blank" rel="noopener">The Origins of Design Engineering</a> (David Luhr), хронологія терміну</>,
    <><a href="https://designbetterpodcast.com/p/design-engineering-handbook" target="_blank" rel="noopener">Design Engineering Handbook</a> (Natalya Shelburne, Adekunle Oduye, Kim Williams, Eddie Lou, 2020)</>,
    <><a href="https://blog.jim-nielsen.com/2022/the-case-for-design-engineers/" target="_blank" rel="noopener">Jim Nielsen: The Case for Design Engineers</a> (2022)</>,
    <><a href="https://www.designengineerjob.com/" target="_blank" rel="noopener">designengineerjob.com</a>, курована дошка вакансій</>,
    <><a href="https://jobs.generalcatalyst.com/companies/anthropic/jobs/79329265-design-engineer-web" target="_blank" rel="noopener">Anthropic: Design Engineer, Web</a></>,
    <><a href="https://www.welcometothejungle.com/en/companies/ramp/jobs/design-engineer_fr_wxsz6zrh" target="_blank" rel="noopener">Ramp: Design Engineer (Brand)</a> (вакансія закрита)</>,
    <><a href="https://jobs.ashbyhq.com/lovable/51885ae5-4f4c-46c4-abd3-d7aad1c8d9c0" target="_blank" rel="noopener">Lovable: Staff / Principal Design Engineer, Web</a></>,
    <><a href="https://cursor.com/careers/design-engineer" target="_blank" rel="noopener">Cursor: Design Engineer</a></>,
    <><a href="https://builtin.com/job/lead-design-technologist/6957812" target="_blank" rel="noopener">Atlassian: Lead Design Technologist</a> (Sydney, вакансія закрита)</>,
    <><a href="https://verifiedinsider.substack.com/p/faq-design-hiring-in-2026" target="_blank" rel="noopener">Tom Scott, Verified Insider: FAQ, Design Hiring in 2026</a></>,
    <><a href="https://uithings.com/design-engineering" target="_blank" rel="noopener">The Complete Guide to Design Engineering (2026)</a> (Tomas Laurinavicius)</>,
    <><a href="https://dou.ua/lenta/articles/salary-report-non-tech-summer-2026/" target="_blank" rel="noopener">DOU: Зарплати фахівців з Design та інших, літо 2026</a></>,
    <><a href="https://dou.ua/lenta/articles/salary-report-devs-summer-2026/" target="_blank" rel="noopener">DOU: Зарплати українських розробників, літо 2026</a></>,
    <><a href="https://jobs.dou.ua/vacancies/?search=design+engineer" target="_blank" rel="noopener">DOU Jobs: пошук «design engineer»</a>, а також повний текстовий аналіз 250 вакансій категорії Design і 88 категорії Front End (зріз 25.08.2026)</>,
    <><a href="https://jobs.dou.ua/companies/cieden/vacancies/367320/" target="_blank" rel="noopener">Cieden: UX Designer (AI-Native / Design Engineer)</a>, <a href="https://jobs.dou.ua/companies/onepage-gmbh/vacancies/369135/" target="_blank" rel="noopener">Onepage: Senior Product Designer</a>, <a href="https://jobs.dou.ua/companies/spaceberry/vacancies/367616/" target="_blank" rel="noopener">Spaceberry Studio: Strong Junior UX/UI Designer</a></>,
    <><a href="https://djinni.co/jobs/?all_keywords=design+engineer" target="_blank" rel="noopener">Djinni: пошук «design engineer»</a> і текстовий аналіз 158 вакансій категорії Design та 58 категорії JavaScript / Front-End, зріз 25.08.2026. Окремо: <a href="https://djinni.co/jobs/844161-product-design-engineer/" target="_blank" rel="noopener">DOOR3, Product Design Engineer</a>, <a href="https://djinni.co/jobs/820758-trainee-ux-ui-engineer/" target="_blank" rel="noopener">jito.dev, Trainee UX/UI engineer</a></>,
    <>DOU, матеріали українських design engineers 2026: <a href="https://dou.ua/forums/topic/60864/" target="_blank" rel="noopener">Марія Нечипорук</a>, <a href="https://dou.ua/forums/topic/61294/" target="_blank" rel="noopener">Денис Осадчий</a>, <a href="https://dou.ua/forums/topic/59081/" target="_blank" rel="noopener">Олена Івлєва</a>, <a href="https://dou.ua/forums/topic/60149/" target="_blank" rel="noopener">Яна Лізгова</a></>,
    <><a href="https://volomydyr.com/" target="_blank" rel="noopener">Володимир Мерленко: Design Engineer plugin для Claude Code</a>; <a href="https://www.youtube.com/watch?v=Uvl-tRga98g" target="_blank" rel="noopener">Anthropic, Dan Cary: Designing with Claude: From prompt to production</a> (Code w/ Claude 2026, Лондон, 19.05.2026); <a href="https://prjctr.com/course/build-your-startup-with-ai" target="_blank" rel="noopener">Projector: Build Your Startup with AI</a>; <a href="http://web.archive.org/web/20260117192300/https://neoversity.com.ua/product-design-m" target="_blank" rel="noopener">Neoversity: HCI &amp; Design для епохи AI</a> (архівна копія)</>,
    <><a href="https://academy.claude.com/" target="_blank" rel="noopener">Claude Academy</a>, безкоштовні курси Anthropic по Claude Code (серпень 2026)</>,
  ),
  ] satisfies Block[],
};
